env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
   'no-console': 'off',
   'import/extensions': 'off',
   'no-await-in-loop': 'off',
   'import/no-mutable-exports': 'off'
}

