name: Make-Lint

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: make lint
